[package]
name = "cid"
version = "0.1.0"
authors = ["Sendy Halim <sendyhalim93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { version = "0.11" }
clap = { version = "2.33" }
serde_json = { version = "1.0.44" }


[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "cid"
path = "src/bin/cid.rs"
