# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on:
  release:
    types:
      - published

name: build_artifacts

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            release_name: macos
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            release_name: linux
            target: x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: [Linux] Install dependencies
        run: |
            sudo apt-get update && apt-get install -y --no-install-recommends \
            pkg-config \
            libssl-dev
        if: matrix.os == 'ubuntu-latest'

      - name: [Linux] Add rust target x86_64-unknown-linux-musl
        run: rustup target add x86_64-unknown-linux-musl
        if: matrix.os == 'ubuntu-latest'

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}

      - uses: actions/upload-artifact@v1
        with:
          name: cid.${{ matrix.release_name }}
          path: ./target/${{ matrix.target }}/release/cid
